services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/motorcycle_inventory
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    platform: linux/arm64
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["mongod", "--bind_ip_all", "--quiet", "--auth"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb://root:example@localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  mongodb_data:
